USE CARAMELO;

CREATE TABLE TB_CLIENTES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_CLIENTE VARCHAR (100),
DATA_NASCIMENTO DATE,
SEXO VARCHAR (100),
EMAIL VARCHAR (100),
TELEFONE VARCHAR (100),
CIDADE VARCHAR (100),
ESTADO VARCHAR (2),
DATA_CADASTRO DATE);

CREATE TABLE TB_PRODUTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO VARCHAR (100),
CATEGORIA VARCHAR (100),
SUBCATEGORIA VARCHAR (100),
MARCA VARCHAR (100),
PREÇO_UNITÁRIO DECIMAL (10,2));

CREATE TABLE TB_VENDAS(
ID_VENDA INT PRIMARY KEY,
DATA_VENDA DATE,
ID_CLIENTE INT, FOREIGN KEY (ID_CLIENTE) REFERENCES
TB_CLIENTES(ID),
ID_PRODUTO INT, FOREIGN KEY (ID_PRODUTO) REFERENCES
TB_PRODUTOS(ID),
QUANTIDADE INT,
FORMA_PAGAMENTO VARCHAR (100),
CANAL_VENDA VARCHAR (100));

SET GLOBAL LOCAL_INFILE = 1;

LOAD DATA INFILE "C:/Users/Steffani.Oliveira/Documents/Repo_Senac/tb_clientes.csv"
INTO TABLE TB_CLIENTES
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NOME_CLIENTE, DATA_NASCIMENTO, SEXO, EMAIL, TELEFONE, CIDADE, ESTADO, DATA_CADASTRO);

LOAD DATA INFILE "C:/Users/Steffani.Oliveira/Documents/Repo_Senac/tb_produtos.csv"
INTO TABLE TB_PRODUTOS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NOME_PRODUTO, CATEGORIA, SUBCATEGORIA, MARCA, PREÇO_UNITÁRIO);

LOAD DATA INFILE "C:/Users/Steffani.Oliveira/Documents/Repo_Senac/tb_vendas.csv"
INTO TABLE TB_VENDAS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_VENDAS;

'''DROP TABLE TB_CLIENTES;

DROP TABLE TB_PRODUTOS;

DROP TABLE TB_VENDAS;'''

#LISTE O TOTAL DE VENDAS REALIZADAS POR CADA FORMA DE PAGAMENTO:
SELECT FORMA_PAGAMENTO, COUNT(*) AS TOTAL_VENDAS
FROM TB_VENDAS
GROUP BY FORMA_PAGAMENTO;

#CALCULE A MÉDIA DE QTD DE PRODUTOS VENDIDOS POR CANAL DE VENDA:
SELECT CANAL_VENDA,
AVG(QUANTIDADE) AS QTD_PROD_VENDIDO
FROM TB_VENDAS
GROUP BY CANAL_VENDA;

#EXIBA APENAS OS CANAIS DE VENDA QUE TIVERAM MAIS DE 100 UNDS VENDIDAS NO TOTAL:
SELECT CANAL_VENDA,
SUM(QUANTIDADE) AS UNIDADES_VENDIDAS
FROM TB_VENDAS
GROUP BY CANAL_VENDA
HAVING UNIDADES_VENDIDAS> 100;

#MOSTRE O TOTAL DE VENDAS POR ESTADO DOS CLIENTES:
SELECT TB_CLIENTES.ESTADO, TB_VENDAS.QUANTIDADE AS VENDAS_ESTADO
FROM TB_CLIENTES
WHERE 
